### ISSUE TITLE
Pactflow dashboard not displaying bi-directional contracts correctly 

### ISSUE THREAD

**Issue by JordanNazemi** [pactflow/roadmap#69]
_Copied from #pactflow board on Slack_

I have three provider branches set up, master and dev are in-line with each other and based on the same commit. The third branch, "test," is meant to mimic a potential feature branch. So far I have not published any consumer contracts. The page looks exactly how I'd imagine it would with two differing contracts being presented across three branches.

**Contract page looks like...**
PROVIDER VERSION: 0d5ba724038b59adfb32a9006af95c330f9cfa76
PROVIDER BRANCH: dev, master
PROVIDER ENV: production, development
CONSUMER VERSION: N/A
CONSUMER BRANCH: N/A
CONSUMER ENV: N/A

PROVIDER VERSION: a067630d2a9c8b07dc63a64ab03606ffe8c727aa
PROVIDER BRANCH: test
PROVIDER ENV: N/A
CONSUMER VERSION: N/A
CONSUMER BRANCH: N/A
CONSUMER ENV: N/A

Now, I'm going to run my pipeline for the dev and master branches of the consumer (who like the provider are based on the same commit). What I EXPECT to see is that there are two separate entries one for dev + master provider to dev + master consumer, and one for test provider to dev + master consumer. HOWEVER, instead,  I see a single entry for the test provider to the dev + master consumer and the dev + master provider contract has just... disappeared. 

**Contract page looks like...**
PROVIDER VERSION: a067630d2a9c8b07dc63a64ab03606ffe8c727aa
PROVIDER BRANCH: test
PROVIDER ENV: N/A
CONSUMER VERSION: e8ffbc486636453a4501b4ea92d6dcff59d5dad1
CONSUMER BRANCH: dev, master
CONSUMER ENV: development, production

**WHEREAS, I'd expected it to look like...**
PROVIDER VERSION: 0d5ba724038b59adfb32a9006af95c330f9cfa76
PROVIDER BRANCH: dev, master
PROVIDER ENV: production, development
CONSUMER VERSION: e8ffbc486636453a4501b4ea92d6dcff59d5dad1
CONSUMER BRANCH: dev, master
CONSUMER ENV: development, production

PROVIDER VERSION: a067630d2a9c8b07dc63a64ab03606ffe8c727aa
PROVIDER BRANCH: test
PROVIDER ENV: N/A
CONSUMER VERSION: e8ffbc486636453a4501b4ea92d6dcff59d5dad1
CONSUMER BRANCH: dev, master
CONSUMER ENV: development, production

**Comment by mefellows** [comment]
Thanks for the report @JordanNazemi, will take a look internally and get back to you.

**Comment by Inksprout** [comment]
Hi @JordanNazemi, thanks for raising this. At the moment this is the expected behaviour for the Overview page. Currently this page supports showing one verification per consumer version, whichever provider version was most recently published will be the verification displayed. 
In your case your test provider was the more recent provider publication so the overview is showing the verification between your consumer version and the test provider. 

Each verification is still generated behind the scenes though, and will work as expected when using 'can-i-deploy' in your build pipeline or via CLI.

We are still working to improve aspects of the Bi-Directional contract UI, including the 'Matrix' view, which will offer a more complete display of each verification that is available.

**Comment by JordanNazemi** [comment]
@Inksprout  Ah understood. Good to hear it's being worked on, thanks for getting back to me! It doesn't functionally make much of a difference but it's made it harder to demo to upper management who tend to overly-focus on the visual dashboard components. I'll close the ticket since I imagine you already have one to add this functionality.
