### ISSUE TITLE
OAS 3.1 Support

### ISSUE THREAD

**Issue by mefellows** [pactflow/roadmap#82]
Adds support for OAS v3.1 in our Bi-Directional Contract Testing Feature (https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas#supported-versions).

**Comment by YOU54F** [comment]
:rocket: Bi-Directional Contract Testing: Release announcement :new:

Just checking in to let you know we have dropped a major update to our Bi-Directional Contract Testing feature.

As a summary, we have released support for:
- :swagger: OAS 3.1
- Full RFC 9110 semantics for media types. TL;DR - content negotiation and vendor specific media types will work a lot better!
- Pact V4 (HTTP interactions)
- Testing negative scenario e.g. checking behaviour for 4xx, 5xx and other error scenarios

Lastly - and most importantly - we have improved how we support the [logical keywords](https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas/keyword-support) anyOf oneOf and allOf, including for use cases in composition, inheritance and polymorphism. These changes improve the guarantees, including ensuring the use of discriminator is correct (instead of ignoring the invalid setup), and simplify the setup previously required to make this work the way you would expect.

:warning: The validation has improved in this release which may cause some tests that were previously passing to now fail. This is a good-bad thing. Good, because we have improved the guarantees, bad because you will need to update your tests to cater for this. See the [changelog](https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas/changelog#july-2023) for advice on addressing these errors :warning:

For a full review of the OAS features we support, see :point_right: https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas/features.

We have also made a number of updates to our documentation, which is much more comprehensive than before including improved “how to fix” [compatibility errors](https://docs.pactflow.io/docs/bi-directional-contract-testing/compatibility-checks), detailed breakdown of our [supported features](https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas/features) and an overview of how we support [keywords](https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas/keyword-support) (an area that seems to trip people up the most)

Lastly, we have created a [helpful repository](https://github.com/pactflow/bdct-oas-examples) of example OpenAPI documents and pact files that can be used to better understand how the features and capabilities translate to real life. This should help bring to life the theoretical documentation.
